#!/usr/bin/env bash

# File where you want to store the data
# will be created if it doesn't already exist
# (make it an absolute path if you don't want it to be in the same directory as
# this script)
LOGFILE=clock-in-out.csv

usage () {
	echo "Usage: clock [in|out]"
	exit 1 
}

# If LOGFILE doesn't exist yet, create it with the column names row
if [[ ! -f $LOGFILE ]]; then
	echo "date,year,month,day,weekday,weeknumber,time,event" > $LOGFILE
fi

# Catch wrong commands and explain how to use the tool
if [[ $# -ne 1 ]]; then
	echo "Wrong number of arguments"
	usage
fi

OPTIONS=("in" "out")

if [[ ! ${OPTIONS[*]} =~ $1 ]]; then
	echo "Wrong argument"
	usage
fi

# Record a clocking event
date "+%Y-%m-%d,%Y,%B,%d,%A,%V,%H:%M:%S,$1" >> $LOGFILE

